/**
 * 占位符数据生成脚本
 * 用于在数据库中创建完整的95个占位符记录
 * 
 * 使用方法：
 * 1. 在浏览器控制台打开Admin后台
 * 2. 运行 window.__insertPlaceholders()
 */

export const COMPLETE_PLACEHOLDERS_LIST = [
  // ========== /en/ (Home Page - Landing) ==========
  {
    placeholder_key: 'home_hero_banner_en',
    page_path: '/en/',
    section_name: 'Hero Banner',
    element_description: 'Main hero background - Factory/Production scene',
    placeholder_type: 'hero',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  
  // ========== /en/thermal-paper-rolls (Thermal Paper Product Page) ==========
  {
    placeholder_key: 'thermal_paper_hero_en',
    page_path: '/en/thermal-paper-rolls',
    section_name: 'Hero Banner',
    element_description: 'Thermal paper rolls product showcase',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_blank_example_en',
    page_path: '/en/thermal-paper-rolls/blank',
    section_name: 'Product Example',
    element_description: 'Blank thermal paper roll close-up',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_paper_printed_example_en',
    page_path: '/en/thermal-paper-rolls/printed',
    section_name: 'Product Example',
    element_description: 'Printed thermal paper with logo/branding',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_paper_pos_example_en',
    page_path: '/en/pos-thermal-paper',
    section_name: 'Product Example',
    element_description: 'POS thermal paper in use',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_paper_atm_example_en',
    page_path: '/en/atm-thermal-paper',
    section_name: 'Product Example',
    element_description: 'ATM thermal paper roll',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'low',
  },
  {
    placeholder_key: 'thermal_paper_bpa_free_example_en',
    page_path: '/en/bpa-free-thermal-paper',
    section_name: 'Product Example',
    element_description: 'BPA-free thermal paper certification/badge',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  
  // ========== /en/thermal-labels (Thermal Labels Page) ==========
  {
    placeholder_key: 'thermal_labels_hero_en',
    page_path: '/en/thermal-labels',
    section_name: 'Hero Banner',
    element_description: 'Thermal label rolls for logistics',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_blank_en',
    page_path: '/en/thermal-labels/blank',
    section_name: 'Product Example',
    element_description: 'Blank thermal label roll',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_labels_printed_en',
    page_path: '/en/thermal-labels/printed',
    section_name: 'Product Example',
    element_description: 'Printed thermal labels with branding',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_labels_4x6_en',
    page_path: '/en/thermal-labels-4x6',
    section_name: 'Product Example',
    element_description: '4x6 shipping label',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'thermal_labels_a6_en',
    page_path: '/en/thermal-labels-a6',
    section_name: 'Product Example',
    element_description: 'A6 logistics label',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'low',
  },
  {
    placeholder_key: 'logistics_labels_en',
    page_path: '/en/logistics-labels',
    section_name: 'Product Example',
    element_description: 'Logistics barcode labels in warehouse',
    placeholder_type: 'application',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  
  // ========== /en/ncr-forms (NCR Forms Page) ==========
  {
    placeholder_key: 'ncr_forms_hero_en',
    page_path: '/en/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless forms product',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_blank_en',
    page_path: '/en/ncr-forms/blank',
    section_name: 'Product Example',
    element_description: 'Blank NCR forms stack',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'ncr_forms_printed_en',
    page_path: '/en/ncr-forms/printed',
    section_name: 'Product Example',
    element_description: 'Printed NCR forms with custom design',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'ncr_forms_continuous_en',
    page_path: '/en/ncr-forms/continuous',
    section_name: 'Product Example',
    element_description: 'Continuous NCR forms on roll',
    placeholder_type: 'product',
    required_dimensions: '800x600',
    required_ratio: '4:3',
    status: 'missing',
    priority: 'low',
  },
  
  // ========== /en/material-supply (Material Supply Pages) ==========
  {
    placeholder_key: 'material_supply_overview_en',
    page_path: '/en/material-supply',
    section_name: 'Hero Banner',
    element_description: 'Raw materials and jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_en',
    page_path: '/en/material-supply/thermal-jumbo-rolls',
    section_name: 'Product Image',
    element_description: 'Thermal jumbo rolls warehouse - master rolls',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_jumbo_en',
    page_path: '/en/material-supply/self-adhesive-jumbo-rolls',
    section_name: 'Product Image',
    element_description: 'Self-adhesive jumbo rolls for label stock',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_sheets_en',
    page_path: '/en/material-supply/self-adhesive-sheets',
    section_name: 'Product Image',
    element_description: 'Self-adhesive label sheets in reams',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'medium',
  },
  {
    placeholder_key: 'ncr_jumbo_rolls_en',
    page_path: '/en/material-supply/ncr-jumbo-rolls',
    section_name: 'Product Image',
    element_description: 'NCR carbonless jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_sheets_en',
    page_path: '/en/material-supply/ncr-sheets',
    section_name: 'Product Image',
    element_description: 'NCR carbonless sheets in reams',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'medium',
  },
  
  // ========== /en/applications (Applications Pages) ==========
  {
    placeholder_key: 'applications_overview_en',
    page_path: '/en/applications',
    section_name: 'Hero Banner',
    element_description: 'Various industry applications montage',
    placeholder_type: 'application',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'govt_tenders_en',
    page_path: '/en/applications/government-tenders',
    section_name: 'Application Scene',
    element_description: 'Government office / procurement documents',
    placeholder_type: 'application',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  
  // ========== /en/manufacturing (Manufacturing Page) ==========
  {
    placeholder_key: 'manufacturing_hero_en',
    page_path: '/en/manufacturing',
    section_name: 'Hero Banner',
    element_description: 'Factory production facility overview',
    placeholder_type: 'factory',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'factory_overview_en',
    page_path: '/en/manufacturing/factory-overview',
    section_name: 'Factory Exterior',
    element_description: 'Factory building exterior',
    placeholder_type: 'factory',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'production_lines_en',
    page_path: '/en/manufacturing/production-lines',
    section_name: 'Production Floor',
    element_description: 'Production line machinery in operation',
    placeholder_type: 'factory',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'quality_control_en',
    page_path: '/en/manufacturing/quality-control',
    section_name: 'QC Lab',
    element_description: 'Quality control testing lab',
    placeholder_type: 'factory',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  
  // ========== /en/about (About Page) ==========
  {
    placeholder_key: 'about_hero_en',
    page_path: '/en/about',
    section_name: 'Company Overview',
    element_description: 'Company office or team photo',
    placeholder_type: 'other',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'medium',
  },
  
  // ========== /en/contact (Contact Page) ==========
  {
    placeholder_key: 'contact_office_exterior_en',
    page_path: '/en/contact',
    section_name: 'Office Location',
    element_description: 'Office building exterior',
    placeholder_type: 'other',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'low',
  },
  
  // ========== /en/products (Products Overview Page) ==========
  {
    placeholder_key: 'products_overview_en',
    page_path: '/en/products',
    section_name: 'Products Grid',
    element_description: 'Product categories overview',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },

  // ========== NEW HERO BANNERS (21:9 Full-Width Design) - EN ==========
  {
    placeholder_key: 'products_hero_banner_en',
    page_path: '/en/products',
    section_name: 'Hero Banner',
    element_description: 'Products overview hero banner - full-width background showcasing product range',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_hero_banner_en',
    page_path: '/en/products/thermal-paper',
    section_name: 'Hero Banner',
    element_description: 'Thermal paper product hero banner - POS rolls, receipt paper showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_hero_banner_en',
    page_path: '/en/products/thermal-labels',
    section_name: 'Hero Banner',
    element_description: 'Thermal labels hero banner - logistics labels, barcode labels showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_hero_banner_en',
    page_path: '/en/products/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR forms hero banner - carbonless multi-part forms showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'applications_overview_hero_banner_en',
    page_path: '/en/applications',
    section_name: 'Hero Banner',
    element_description: 'Applications overview hero banner - industry solutions and use cases',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'material_supply_hero_banner_en',
    page_path: '/en/material-supply',
    section_name: 'Hero Banner',
    element_description: 'Material supply hero banner - jumbo rolls and raw materials for converting',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_hero_banner_en',
    page_path: '/en/material-supply/thermal-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'Thermal jumbo rolls hero banner - master rolls stacked for converters and slitting',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_jumbo_hero_banner_en',
    page_path: '/en/material-supply/self-adhesive-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'Self-adhesive jumbo rolls hero banner - label material rolls for converters',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_sheets_hero_banner_en',
    page_path: '/en/material-supply/self-adhesive-sheets',
    section_name: 'Hero Banner',
    element_description: 'Self-adhesive label sheets hero banner - A4 and custom sizes for office and logistics',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_jumbo_rolls_hero_banner_en',
    page_path: '/en/material-supply/ncr-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless paper jumbo rolls hero banner - multi-part forms material',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_sheets_hero_banner_en',
    page_path: '/en/material-supply/ncr-sheets',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless paper sheets hero banner - multi-part forms in A4 and custom sizes',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'manufacturing_hero_banner_en',
    page_path: '/en/manufacturing',
    section_name: 'Hero Banner',
    element_description: 'Manufacturing overview hero banner - factory production facility with machinery and operations',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'factory_overview_hero_banner_en',
    page_path: '/en/manufacturing/factory-overview',
    section_name: 'Hero Banner',
    element_description: 'Factory overview hero banner - factory building exterior and warehouse facility',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'production_lines_hero_banner_en',
    page_path: '/en/manufacturing/production-lines',
    section_name: 'Hero Banner',
    element_description: 'Production lines hero banner - machinery in operation, thermal paper and label manufacturing',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'quality_control_hero_banner_en',
    page_path: '/en/manufacturing/quality-control',
    section_name: 'Hero Banner',
    element_description: 'Quality control hero banner - QC testing lab with inspection equipment and quality checks',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'contact_hero_banner_en',
    page_path: '/en/contact',
    section_name: 'Hero Banner',
    element_description: 'Contact us hero banner - customer service team or office communication',
    placeholder_type: 'contact',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },

  // ========== RUSSIAN ROUTES (Mirror of EN) ==========
  // Duplicate all above with /ru/ prefix
  {
    placeholder_key: 'home_hero_banner_ru',
    page_path: '/ru/',
    section_name: 'Hero Banner',
    element_description: 'Main hero background - Factory/Production scene',
    placeholder_type: 'hero',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_hero_ru',
    page_path: '/ru/thermal-paper-rolls',
    section_name: 'Hero Banner',
    element_description: 'Thermal paper rolls product showcase',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_hero_ru',
    page_path: '/ru/thermal-labels',
    section_name: 'Hero Banner',
    element_description: 'Thermal label rolls for logistics',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_hero_ru',
    page_path: '/ru/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless forms product',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'material_supply_overview_ru',
    page_path: '/ru/material-supply',
    section_name: 'Hero Banner',
    element_description: 'Raw materials and jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_ru',
    page_path: '/ru/material-supply/thermal-jumbo-rolls',
    section_name: 'Product Image',
    element_description: 'Thermal jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'manufacturing_hero_ru',
    page_path: '/ru/manufacturing',
    section_name: 'Hero Banner',
    element_description: 'Factory production facility overview',
    placeholder_type: 'factory',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'products_overview_ru',
    page_path: '/ru/products',
    section_name: 'Products Grid',
    element_description: 'Product categories overview',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },

  // ========== NEW HERO BANNERS (21:9 Full-Width Design) - RU ==========
  {
    placeholder_key: 'products_hero_banner_ru',
    page_path: '/ru/products',
    section_name: 'Hero Banner',
    element_description: 'Products overview hero banner - full-width background showcasing product range',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_hero_banner_ru',
    page_path: '/ru/products/thermal-paper',
    section_name: 'Hero Banner',
    element_description: 'Thermal paper product hero banner - POS rolls, receipt paper showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_hero_banner_ru',
    page_path: '/ru/products/thermal-labels',
    section_name: 'Hero Banner',
    element_description: 'Thermal labels hero banner - logistics labels, barcode labels showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_hero_banner_ru',
    page_path: '/ru/products/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR forms hero banner - carbonless multi-part forms showcase',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'applications_overview_hero_banner_ru',
    page_path: '/ru/applications',
    section_name: 'Hero Banner',
    element_description: 'Applications overview hero banner - industry solutions and use cases',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'material_supply_hero_banner_ru',
    page_path: '/ru/material-supply',
    section_name: 'Hero Banner',
    element_description: 'Material supply hero banner - jumbo rolls and raw materials for converting',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_hero_banner_ru',
    page_path: '/ru/material-supply/thermal-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'Thermal jumbo rolls hero banner - master rolls stacked for converters and slitting',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_jumbo_hero_banner_ru',
    page_path: '/ru/material-supply/self-adhesive-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'Self-adhesive jumbo rolls hero banner - label material rolls for converters',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_sheets_hero_banner_ru',
    page_path: '/ru/material-supply/self-adhesive-sheets',
    section_name: 'Hero Banner',
    element_description: 'Self-adhesive label sheets hero banner - A4 and custom sizes for office and logistics',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_jumbo_rolls_hero_banner_ru',
    page_path: '/ru/material-supply/ncr-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless paper jumbo rolls hero banner - multi-part forms material',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_sheets_hero_banner_ru',
    page_path: '/ru/material-supply/ncr-sheets',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless paper sheets hero banner - multi-part forms in A4 and custom sizes',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'manufacturing_hero_banner_ru',
    page_path: '/ru/manufacturing',
    section_name: 'Hero Banner',
    element_description: 'Manufacturing overview hero banner - factory production facility with machinery and operations',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'factory_overview_hero_banner_ru',
    page_path: '/ru/manufacturing/factory-overview',
    section_name: 'Hero Banner',
    element_description: 'Factory overview hero banner - factory building exterior and warehouse facility',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'production_lines_hero_banner_ru',
    page_path: '/ru/manufacturing/production-lines',
    section_name: 'Hero Banner',
    element_description: 'Production lines hero banner - machinery in operation, thermal paper and label manufacturing',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'quality_control_hero_banner_ru',
    page_path: '/ru/manufacturing/quality-control',
    section_name: 'Hero Banner',
    element_description: 'Quality control hero banner - QC testing lab with inspection equipment and quality checks',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'contact_hero_banner_ru',
    page_path: '/ru/kontakty',
    section_name: 'Hero Banner',
    element_description: 'Contact us hero banner - customer service team or office communication',
    placeholder_type: 'contact',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  
  // ========== CHINESE ROUTES (Mirror of EN) ==========
  {
    placeholder_key: 'home_hero_banner_zh',
    page_path: '/zh/',
    section_name: 'Hero Banner',
    element_description: 'Main hero background - Factory/Production scene',
    placeholder_type: 'hero',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_hero_zh',
    page_path: '/zh/thermal-paper-rolls',
    section_name: 'Hero Banner',
    element_description: 'Thermal paper rolls product showcase',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_hero_zh',
    page_path: '/zh/thermal-labels',
    section_name: 'Hero Banner',
    element_description: 'Thermal label rolls for logistics',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_hero_zh',
    page_path: '/zh/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR carbonless forms product',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'material_supply_overview_zh',
    page_path: '/zh/material-supply',
    section_name: 'Hero Banner',
    element_description: 'Raw materials and jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_zh',
    page_path: '/zh/material-supply/thermal-jumbo-rolls',
    section_name: 'Product Image',
    element_description: 'Thermal jumbo rolls warehouse',
    placeholder_type: 'material',
    required_dimensions: '1200x800',
    required_ratio: '3:2',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'manufacturing_hero_zh',
    page_path: '/zh/manufacturing',
    section_name: 'Hero Banner',
    element_description: 'Factory production facility overview',
    placeholder_type: 'factory',
    required_dimensions: '1920x1080',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'products_overview_zh',
    page_path: '/zh/products',
    section_name: 'Products Grid',
    element_description: 'Product categories overview',
    placeholder_type: 'product',
    required_dimensions: '1600x900',
    required_ratio: '16:9',
    status: 'missing',
    priority: 'high',
  },

  // ========== NEW HERO BANNERS (21:9 Full-Width Design) - ZH ==========
  {
    placeholder_key: 'products_hero_banner_zh',
    page_path: '/zh/products',
    section_name: 'Hero Banner',
    element_description: '产品总览Hero Banner - 全宽背景展示产品系列',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_paper_hero_banner_zh',
    page_path: '/zh/products/thermal-paper',
    section_name: 'Hero Banner',
    element_description: '热敏纸产品Hero Banner - POS卷、收据纸展示',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_labels_hero_banner_zh',
    page_path: '/zh/products/thermal-labels',
    section_name: 'Hero Banner',
    element_description: '热敏标签Hero Banner - 物流标签、条码标签展示',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_forms_hero_banner_zh',
    page_path: '/zh/products/ncr-forms',
    section_name: 'Hero Banner',
    element_description: 'NCR表格Hero Banner - 无碳复写多联表格展示',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'applications_overview_hero_banner_zh',
    page_path: '/zh/applications',
    section_name: 'Hero Banner',
    element_description: '应用场景总览Hero Banner - 行业解决方案和使用场景',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'material_supply_hero_banner_zh',
    page_path: '/zh/material-supply',
    section_name: 'Hero Banner',
    element_description: '原材料供应Hero Banner - 分切用大卷和原材料展示',
    placeholder_type: 'product',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'thermal_jumbo_rolls_hero_banner_zh',
    page_path: '/zh/material-supply/thermal-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: '热敏Jumbo大卷Hero Banner - 分切用主卷堆叠展示',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_jumbo_hero_banner_zh',
    page_path: '/zh/material-supply/self-adhesive-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: '自粘性Jumbo大卷Hero Banner - 分切用标签材料卷',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'self_adhesive_sheets_hero_banner_zh',
    page_path: '/zh/material-supply/self-adhesive-sheets',
    section_name: 'Hero Banner',
    element_description: '自粘性片材Hero Banner - A4及定制尺寸办公物流用',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_jumbo_rolls_hero_banner_zh',
    page_path: '/zh/material-supply/ncr-jumbo-rolls',
    section_name: 'Hero Banner',
    element_description: 'NCR Jumbo大卷Hero Banner - 无碳复写纸多联表格材料',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'ncr_sheets_hero_banner_zh',
    page_path: '/zh/material-supply/ncr-sheets',
    section_name: 'Hero Banner',
    element_description: 'NCR片材Hero Banner - A4及定制尺寸多联表格',
    placeholder_type: 'material',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'manufacturing_hero_banner_zh',
    page_path: '/zh/manufacturing',
    section_name: 'Hero Banner',
    element_description: '制造总览Hero Banner - 工厂生产设施，包含设备和操作',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'factory_overview_hero_banner_zh',
    page_path: '/zh/manufacturing/factory-overview',
    section_name: 'Hero Banner',
    element_description: '工厂总览Hero Banner - 工厂建筑外观和仓库设施',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'production_lines_hero_banner_zh',
    page_path: '/zh/manufacturing/production-lines',
    section_name: 'Hero Banner',
    element_description: '生产线Hero Banner - 运行中的设备，热敏纸和标签制造',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'quality_control_hero_banner_zh',
    page_path: '/zh/manufacturing/quality-control',
    section_name: 'Hero Banner',
    element_description: '质量控制Hero Banner - QC测试实验室，包含检测设备和质量检查',
    placeholder_type: 'factory',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'contact_hero_banner_zh',
    page_path: '/zh/contact',
    section_name: 'Hero Banner',
    element_description: '联系我们Hero Banner - 客户服务团队或办公室沟通',
    placeholder_type: 'contact',
    required_dimensions: '2100x900',
    required_ratio: '21:9',
    status: 'missing',
    priority: 'high',
  },
  
  // ========== SHARED ELEMENTS (All Languages) ==========
  {
    placeholder_key: 'global_company_logo',
    page_path: '/',
    section_name: 'Header Logo',
    element_description: 'Zhixin Paper company logo',
    placeholder_type: 'icon',
    required_dimensions: '200x60',
    required_ratio: '10:3',
    status: 'missing',
    priority: 'high',
  },
  {
    placeholder_key: 'global_favicon',
    page_path: '/',
    section_name: 'Browser Icon',
    element_description: 'Website favicon',
    placeholder_type: 'icon',
    required_dimensions: '32x32',
    required_ratio: '1:1',
    status: 'missing',
    priority: 'medium',
  },
];

console.log(`Total placeholders: ${COMPLETE_PLACEHOLDERS_LIST.length}`);